### ISSUE TITLE
ng new myproject

### ISSUE THREAD

**Issue by fayeyen** [mutanttech/angular4-cli-boilerplate#2]
Think ng new myproject can bring the standard angular4 boilerplate. What the point?Don't get your different or better?

Regards,
Yen

**Comment by mutanttech** [comment]
When I was doing initial setup I had to face problems making it work. But once it was setup, I kept is as a repo so that I can save those hours which I spent fixing the setup for the first time. I am not sure what you are looking for.

**Comment by fayeyen** [comment]
Thank you! I'm looking from framework, any suggestion.

**Comment by mutanttech** [comment]
I didn't understand what you meant, can you please elaborate.. Thanks !

**Comment by fayeyen** [comment]
use angular cli, command ng new project.
Best Regards,
Yen

**Comment by mutanttech** [comment]
You can refer to this link step by step: https://github.com/angular/angular-cli
I think that will help..
Regards !
